#version 450

#include "dequant_head.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer A {block_rocmfpx_fp6 data_a[];};
layout (binding = 1) writeonly buffer D {D_TYPE data_b[];};

void main() {
    const uint i = gl_GlobalInvocationID.x;

#ifdef NEEDS_INIT_IQ_SHMEM
    init_iq_shmem(gl_WorkGroupSize);
#endif

    if (i >= p.nel) {
        return;
    }
    const uint ib = i / 32u;
    const uint idx = i & 31u;
    const i8vec4 unpacked = unpack8(rocmfpx_fp6_pack4_qs(data_a[ib].qs, idx & ~3u));
    const float q = float(unpacked[idx & 3u]);
    const float d = ue4m3_to_fp32(data_a[ib].e[idx >= 16u ? 1u : 0u]);
    data_b[i] = D_TYPE(d * q);
}
